"""Initial

Revision ID: dd98e207ff1c
Revises: 
Create Date: 2022-07-08 01:53:52.183016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd98e207ff1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olx_egypt',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('URL', sa.String(), nullable=True),
    sa.Column('Breadcrumb', sa.String(), nullable=True),
    sa.Column('Price', sa.String(), nullable=True),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('Type', sa.String(), nullable=True),
    sa.Column('Bedrooms', sa.String(), nullable=True),
    sa.Column('Bathrooms', sa.String(), nullable=True),
    sa.Column('Area', sa.String(), nullable=True),
    sa.Column('Location', sa.String(), nullable=True),
    sa.Column('Compound', sa.String(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('Seller_member_since', sa.String(), nullable=True),
    sa.Column('Seller_phone_number', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Amenities', sa.String(), nullable=True),
    sa.Column('Reference', sa.String(), nullable=True),
    sa.Column('Listed_date', sa.String(), nullable=True),
    sa.Column('Level', sa.String(), nullable=True),
    sa.Column('Payment_option', sa.String(), nullable=True),
    sa.Column('Delivery_term', sa.String(), nullable=True),
    sa.Column('Furnished', sa.String(), nullable=True),
    sa.Column('Delivery_date', sa.String(), nullable=True),
    sa.Column('Down_payment', sa.String(), nullable=True),
    sa.Column('Image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('olx_egypt')
    # ### end Alembic commands ###
